### PR TITLE
Support for BlockMen's beds mod

### PR DESCRIPTION
**Pull request by Miner59**
Since BlockMen recently added his beds mod to default minetest game I added code to read the saved positions from this mod, too.
Although I made some other small improvements.

### CODE REVIEW

**Comment by Kilarin** [comment]
This looks fantastic!  Give me a little bit to test, and I'll have it merged.  Thank you very much!

**Comment by Kilarin** [comment]
When creating a new world in minetest using only compassgps as a mod, I'm getting this:

18:49:39: ERROR[main]: ServerError: /home/donald/.minetest/mods/compassgps/init.lua:957: attempt to compare number with nil
18:49:39: ERROR[main]: stack traceback:
18:49:39: ERROR[main]:  /home/donald/.minetest/mods/compassgps/init.lua:957: in function 'get_default_bookmark'
18:49:39: ERROR[main]:  /home/donald/.minetest/mods/compassgps/init.lua:1030: in function </home/donald/.minetest/mods/compassgps/init.lua:989>
18:49:39: ERROR[main]:  /usr/share/minetest/builtin/game/register.lua:341: in function </usr/share/minetest/builtin/game/register.lua:329>

**Comment by Miner59** [comment]
Sorry, I forgot I needed to change some more lines...
Now this pull request should be good, I commit a bugfix.

**Comment by Kilarin** [comment]
Looks great, thank you VERY much!

**Pull request merged**
